### ISSUE TITLE
sbt.librarymanagement.ResolveException

### ISSUE THREAD

**Issue by letusfly85** [StreetContxt/kcl-akka-stream#114]
Resolver exception happens on `sbt update`.

@angelo-streetcontxt 

The following URL is broken, did you change the several settings on the maven repository?

https://dl.bintray.com/streetcontxt/maven/com/streetcontxt/kcl-akka-stream_2.12/4.1.0

The comments on the issue below didn't work for me.

https://github.com/StreetContxt/kcl-akka-stream/pull/21

> resolvers in ThisBuild += Resolver.bintrayRepo("streetcontxt", "maven")

**Comment by angelo-streetcontxt** [comment]
Apologies, I apparently forgot to update the docs, I'll take care of that over the weekend.
Our group ID and version number changed, the current releases are on maven central

Please see https://github.com/StreetContxt/kcl-akka-stream/issues/87 for details

**Comment by letusfly85** [comment]
@angelo-streetcontxt 

Thank you!
It worked 🎉 

I will close this issue.
