### ISSUE TITLE
Upgrading to KCL 2.x

### ISSUE THREAD

**Issue by ukayani** [StreetContxt/kcl-akka-stream#15]
Are there any plans to update this library to support KCL 2.x ? There are some breaking changes for the interfaces that are currently implemented.

Thank you for the library!

**Comment by anikifoss** [comment]
Based on the number of bugfixes in KCL 2.0.1 release notes, it looks like they are still stabilizing the new library. At this pace, I would assume between half a year to a year before all the issues are fixed, or workarounds are easily searchable.

To answer your question, I would not attempt to upgrade to KCL 2 for at least another year.

**Comment by ewestern** [comment]
I definitely understand the desire to wait a while on this.
That said, I'm going to need to use enhanced fan-out soon, which will require KCL 2.*, so I'll probably end up forking this and doing my own upgrade.
Just another data point to consider ;)

**Comment by ukayani** [comment]
@ewestern  I ended up rewriting using KCL 2.x. Take a look at the examples folder for examples. I haven't released it on maven yet (we have it in a private package repo for now).  Have been using it on production streams for over a few months now.

https://github.com/500px/kinesis-stream

**Comment by ewestern** [comment]
@ukayani Oh, that's great!
I'll definitely check it out. Thanks!
