### ISSUE TITLE
Worker shutdown upon stream failure

### ISSUE THREAD

**Issue by ukayani** [StreetContxt/kcl-akka-stream#16]
Hi,

The KCL worker is not properly shut down when downstream stages signal a failure.

For example, if i have the source connected to a mapAsync stage which fails. The stream terminates but the worker which was started by the KinesisSource does not get cleaned up. A cleanup only occurs if the actor system is terminated.

**Comment by anikifoss** [comment]
Hi @ukayani,

Can you please provide a complete runnable example of the issue you are experiencing. Or, even better, can you add a test case to this test suite that exposes the failure:
https://github.com/StreetContxt/kcl-akka-stream/blob/f224a42ab6b0ee937280679c7c296ac9e8f508cd/src/test/scala/com/contxt/kinesis/KinesisSourceFactoryTest.scala

**Comment by anikifoss** [comment]
Could not reproduce. Closing for now due to inactivity. Please re-open with a code sample if the issue comes up again.
