### ISSUE TITLE
KCL stuck

### ISSUE THREAD

**Issue by abhiranjan** [StreetContxt/kcl-akka-stream#20]
I am using kcl-akka-stream for large scale continuous data processing which will soon be in prod environment.
Very often I am seeing that even though data is coming in kinesis stream continuously but, consumer stats suggests that nothing is getting consumed.
<img width="408" alt="image" src="https://user-images.githubusercontent.com/2917427/70499926-448a6980-1b40-11ea-9a8c-0a23ff8521f2.png">

After I restart the consumer application, I see a spike :
<img width="462" alt="image" src="https://user-images.githubusercontent.com/2917427/70499913-350b2080-1b40-11ea-9582-7c8eef5ea11e.png">

After a little bit of research I found this: https://github.com/awslabs/amazon-kinesis-client/issues/185. Can somebody please help me understand if that's indeed the issue?

I am using version 2.0.3.
`"com.streetcontxt" %% "kcl-akka-stream" % "2.0.3"
`

**Comment by anikifoss** [comment]
Thanks for reporting the issue. Could you double check that you are calling `message.markProcessed()` for all messages. If there is even one message not marked as processed, the stream will halt, as it's designed to guaranteed at-least-once processing and ensure no messages are ever accidentally lost.

**Comment by abhiranjan** [comment]
@lexn82 Yes I can confirm that all the events are being checkpointed.
Additionally, I had a discussion with Amazon on this they suggested library upgrade to 2.2.7 and see if we are able to reproduce the problem.

Meanwhile, as mentioned  here awslabs/amazon-kinesis-client#185. I have setup a cron job to restart services daily which seems to be solving the problem interim.

**Comment by angelo-streetcontxt** [comment]
The 3.0.0 release of the library now runs with the amazon kinesis client version 2.2.7

I'll close this issue for the time being, please feel free to open a new one if you still have issues
