### ISSUE TITLE
idleTimeBetweenReadsInMillis

### ISSUE THREAD

**Issue by shahrakesh** [StreetContxt/kcl-akka-stream#39]
Hi,

This is more of a query rather than issue. Can you please advise how can I set the idleTimeBetweenReadsInMillis value? I believe its set to 1 second by default as per https://docs.aws.amazon.com/streams/latest/dev/kinesis-low-latency.html.

Thanks
Rakesh

**Comment by bpg-dev** [comment]
Hi @shahrakesh!

Sorry for the late reply. The option you're referring to [has been removed in KCL 2.x]( https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html#client-configuration), which is the base for the current `kcl-akka-stream` v3.x. Now you can use `ConsumerConfig.withCoordinatorConfig(...)` factory method to supply an instance of customized `CoordinatorConfig` with required [`shardConsumerDispatchPollIntervalMillis`](https://github.com/awslabs/amazon-kinesis-client/blob/3e32ff190687e7a34274923d36f640d337298c35/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/CoordinatorConfig.java#L68) value. 

Hope this helps

**Comment by bpg-dev** [comment]
@shahrakesh I'm closing this issue, please reopen if you have any additional questions.

**Comment by shahrakesh** [comment]
That's very helpful. Thanks for your response.
