### ISSUE TITLE
Migrate artifacts away from https://dl.bintray.com/streetcontxt/maven/

### ISSUE THREAD

**Issue by stku1985** [StreetContxt/kcl-akka-stream#87]
Hello all,

jfrog will sunset bintray on May 1st, 2021; see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/. Hence the need to migrate to another public maven repository.

Could you please look into that?

Kind regards.

**Comment by agenovese** [comment]
We're aware of yesterday's announcement, we're looking into the alternatives to select another hosting option and will update the readme (and this ticket) once we've selected one

**Comment by AWare** [comment]
Hi, this date is fast approaching, and we're starting to see [inavailability](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Has there been any progress on this?

**Comment by angelo-streetcontxt** [comment]
Just finishing up the last item on my backlog before this, I'll be moving on to this work Tomorrow.

**Comment by AWare** [comment]
Hi, apologies for nagging, but how is this going?

**Comment by agenovese** [comment]
We have a new version of the library up on Maven Central at `"io.github.streetcontxt" %% "kcl-akka-stream" % "5.0.0"`
This release is the same code as 4.1.0 with dependencies updated and the coordinates changed.

I've got one more, unrelated, OSS project to move over and then I intend to attempt to make a branch off of 4.1.0 and build a 4.1.1 release that is just the coordinate change

**Comment by angelo-streetcontxt** [comment]
2 new releases now up on OSSRH & Central:

`"io.github.streetcontxt" %% "kcl-akka-stream" % "5.0.0"` - Same code as 4.1.0, updated dependencies, updated coordinates
`"io.github.streetcontxt" %% "kcl-akka-stream" % "4.1.1"` - Same code as 4.1.0, same dependencies, updated coordinates

At this point, the rest of the work on this ticket shouldn't really impact down stream code, it's basically just some housekeeping work. If you run into any issues with the new releases, please let us know.

TODOs before I close out this ticket:

- [x] Update README

- [x] Get branch builds setup in GH Actions
- [x] Move to using the "official" scala steward setup as opposed to Street Contxt's internal run 
(we've made some changes to it that aren't really meant for OSS projects)

**Comment by AWare** [comment]
Thank you :)
